version: '3'

services:
    web:
        build: .
        ports:
            - 9000:8080
            - 8000:8000
        volumes:
            - ./share:/app
        stdin_open: true
        tty: true
